# Generated by Django 3.2.5 on 2021-07-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doc_no', models.IntegerField()),
                ('received_from', models.CharField(blank=True, max_length=200, null=True)),
                ('receipt_no', models.IntegerField()),
                ('issue', models.CharField(blank=True, max_length=200, null=True)),
                ('balance', models.IntegerField()),
                ('verification_date', models.DateField()),
                ('verified_by', models.CharField(max_length=100)),
            ],
        ),
    ]
