# Generated by Django 3.2.5 on 2021-07-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bincardcreation', '0002_alter_material_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='receipt_no',
            field=models.IntegerField(unique=True),
        ),
    ]
