# Generated by Django 3.2.5 on 2021-08-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bincardcreation', '0006_material_material_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='receipt_no',
        ),
    ]
