# Generated by Django 3.2.5 on 2021-08-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bincardcreation', '0003_alter_material_receipt_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_name',
            field=models.CharField(choices=[('key board', 'key board'), ('mouse', 'mouse'), ('phone', 'phone'), ('labtop', 'laptop')], default='phone', max_length=100),
        ),
        migrations.AddField(
            model_name='material',
            name='transaction_type',
            field=models.CharField(choices=[('RF', 'Recieved from'), ('IT', 'Issued to')], default='RF', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='doc_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='receipt_no',
            field=models.IntegerField(),
        ),
    ]
