# Generated by Django 3.2.5 on 2021-08-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bincardcreation', '0004_auto_20210803_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='material_name',
        ),
    ]
