# Generated by Django 3.2.5 on 2021-08-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bincardcreation', '0005_remove_material_material_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_name',
            field=models.CharField(choices=[('key board', 'key board'), ('mouse', 'mouse'), ('phone', 'phone'), ('labtop', 'laptop')], default='phone', max_length=100),
        ),
    ]
